### ISSUE TITLE
dogwater

### ISSUE THREAD

**Issue by pyroTM** [moonyaim/python-learner-guide#3]
fix ur stuff smh

**Comment by moonyaim** [comment]
@Sashi-boi wrote most of the stuff

**Comment by Sashi-boi** [comment]
he was only talking abt the levels of coding
but i removed it

**Comment by pyroTM** [comment]
> @Sashi-boi wrote most of the stuff. If you want, I'm happily welcome for you to fork the repository and make a pull request with any changes you see fit
> 
> Best, Vik (moonyaim)

why r u so formal smh

**Comment by moonyaim** [comment]
Not my fault i want to be civil

**Comment by Sashi-boi** [comment]
bruh bs
